### PR TITLE
[CDP-400] Backport S3A metrics2 implementation

### PR DESCRIPTION
**Pull request by noahchr**
Still need to do performance testing, etc. before this can be merged. Opening a PR now so we can track this work.

The S3A metrics instrumentation was integrated with Hadoop's metrics2 framework in these two changes from Hadoop 3.1.0.
- [HADOOP-14475](https://github.com/apache/hadoop/commit/6555af81a26b0b72ec3bee7034e01f5bd84b1564): Metrics of S3A don't print out when enabled
- [HADOOP-15161](https://github.com/apache/hadoop/commit/b62a5ece95a6b5bbb17f273debd55bcbf0c5f28c): Stream and common statistics missing from metrics

### Testing
Build
```
mvn --projects hadoop-aws clean package -DskipTests
```
Replace `hadoop-aws-2.9.2.jar` in Hadoop CLI `share/hadoop/tools/lib`

Configure `$HADOOP_HOME/hadoop-metrics2.properties`
```
*.period=10
s3a-file-system.sink.file.class=org.apache.hadoop.metrics2.sink.FileSink
s3a-file-system.sink.file.filename=/Users/noah/metrics.txt
```
Exercise S3A filesystem codepath
```
hadoop fs -ls s3a://aiq-artifacts-30d/...
```
Validate metrics `/Users/noah/metrics.txt`
```
1584463079431 s3aFileSystem.s3aFileSystem: Context=s3aFileSystem, s3aFileSystemId=99f84dc7-fe38-430e-98ce-e905bf170d14, bucket=aiq-artifacts-30d, Hostname=ip-192-168-1-171.ec2.internal, stream_opened=0, stream_close_operations=0, stream_closed=0, stream_aborted=0, stream_seek_operations=0, stream_read_exceptions=0, stream_forward_seek_operations=0, stream_backward_seek_operations=0, stream_bytes_skipped_on_seek=0, stream_bytes_backwards_on_seek=0, stream_bytes_read=0, stream_read_operations=0, stream_read_fully_operations=0, stream_read_operations_incomplete=0, stream_bytes_read_in_close=0, stream_bytes_discarded_in_abort=0, files_created=0, files_copied=0, files_copied_bytes=0, files_deleted=0, fake_directories_deleted=0, directories_created=0, directories_deleted=0, ignored_errors=0, op_copy_from_local_file=0, op_create=0, op_create_non_recursive=0, op_delete=0, op_exists=0, op_get_file_status=1, op_glob_status=1, op_is_directory=0, op_is_file=0, op_list_files=0, op_list_located_status=0, op_list_status=0, op_mkdirs=0, op_open=0, op_rename=0, object_copy_requests=0, object_delete_requests=0, object_list_requests=0, object_continue_list_requests=0, object_metadata_requests=1, object_multipart_aborted=0, object_put_bytes=0, object_put_requests=0, object_put_requests_completed=0, stream_write_failures=0, stream_write_block_uploads=0, stream_write_block_uploads_committed=0, stream_write_block_uploads_aborted=0, stream_write_total_time=0, stream_write_total_data=0, s3guard_metadatastore_put_path_request=0, s3guard_metadatastore_initialization=0, object_put_requests_active=0, object_put_bytes_pending=0, stream_write_block_uploads_active=0, stream_write_block_uploads_pending=0, stream_write_block_uploads_data_pending=0, S3guard_metadatastore_put_path_latencyNumOps=0, S3guard_metadatastore_put_path_latency50thPercentileLatency=0, S3guard_metadatastore_put_path_latency75thPercentileLatency=0, S3guard_metadatastore_put_path_latency90thPercentileLatency=0, S3guard_metadatastore_put_path_latency95thPercentileLatency=0, S3guard_metadatastore_put_path_latency99thPercentileLatency=0
```
Summary
```
op_get_file_status=1,
op_glob_status=1,
object_metadata_requests=1
```

### CODE REVIEW

**Comment by MasterDDT** [comment]
Did you actually run that new test? You should be able to `mvn ... -DskipTests=false` to run it

**Comment by mrwiggles** [comment]
@noahchr Excellent work on backporting the metrics support!

I'd echo Mitesh and see if you can run these additional tests. Approving with the understanding that you will.

PS. Looks like around 40 metrics are being recorded, so 40 individual log lines per period.

**Comment by mrwiggles** [comment]
@noahchr Should we just merge this now? Or are you anticipating additional changes?

**Comment by mrwiggles** [comment]
@noahchr Should we just merge this now? Or are you anticipating additional changes?

**Comment by noahchr** [comment]
```
Tests run: 210, Failures: 0, Errors: 0, Skipped: 2
```
Tests all pass

**Pull request merged**
